version: '3'

services:
  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .db-data/:/var/lib/postgresql/data/

    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:4.23
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database
    env_file:
      - .env

volumes:
  database:
  pgadmin: